### ISSUE TITLE
Add more documentation examples for the various supported languages

### ISSUE THREAD

**Issue by Mertsch** [geeklearningio/gl-vsts-tasks-file-patch#13]
This issue is related to the comment on https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-file-patch&showReviewDialog=true

> May we ask a bit more details about the struggle with XML patch so we can improve our documentation accordingly? Is it related to XPath syntax or was it something else?

What I mean is that this page
https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/How-to-use-Slick-Syntax
is great as it shows a very simple, yet enough example to get started.

while this page
https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/Patch-XML-Files
contains no examples at all (taking into account the slick syntax is already covered)

I wish there was a similar example as with the slick syntax for the full syntax. I would *not* expect you to explain XPath, as this is pretty well documented. Just maybe have a link to an examples page like this great resource https://tools.ietf.org/html/rfc5261#appendix-A

Also it may sound strange, but I did not notice the "Syntax Type" combobox at the top at all and wondered why my slick syntax isn't accepted maybe it can be placed closer to the actual syntax box.

**Comment by sandorfr** [comment]
I did not follow up, but this is definitely great feedback and we plan on improving those documentations soon.
