### ISSUE TITLE
Not recognizing date/time build variables

### ISSUE THREAD

**Issue by jdshkolnik** [geeklearningio/gl-vsts-tasks-file-patch#15]
This...

`= /Version => "$(GitVersion.MajorMinorPatch).$(Date:yyyyMMdd)_$(Hours)$(Minutes)$(Seconds)"`

...comes out as this...

`0.1.0.undefined_undefinedundefinedundefined`

**Comment by michshat** [comment]
I get the same `undefined.undefined` when using `= /version => "$(date:yyyyMMdd).$(rev:.r)"`  

Any idea?

**Comment by sandorfr** [comment]
The formatting on dates and revision number is only valid for build numbers.
But in what seems to be your scenarios why not use the `Build.BuildNumber` variable since it seems it's what your are trying to achieve ?

**Comment by jdshkolnik** [comment]
Build.BuildNumber variable gets overwritten by GitVersion so by that point it's already something else.
