### ISSUE TITLE
Failed to Patch XML File

### ISSUE THREAD

**Issue by brett3210** [geeklearningio/gl-vsts-tasks-file-patch#16]
I am trying to update the DacVersion and DacApplicationName in an XML .sqlproj file:
[TestSQLServerDBProj.TXT](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/files/670359/TestSQLServerDBProj.TXT)
using the Patch XML Files Task, but receive the following errors:
2016-12-23T06:16:03.6605141Z /Project/PropertyGroup/DacVersion was not found
2016-12-23T06:16:03.6645136Z Error: Failed to patch xml file

The "Slick Syntax" I'm using is:
= /Project/PropertyGroup/DacVersion => "$(Build.BuildNumber)"
= /Project/PropertyGroup/DacApplicationName => "TestSQLServerDBProj$(Build.BuildNumber)"

Is there something silly I'm missing?

**Comment by sandorfr** [comment]
Hi @brett3210, 

Most elements is Visual Studio project files belong to msbuild namespace, hence it must be specified in the XPath expression.

To achieve what you are trying to do, you should use: 
*  Namespaces
    ```
    msbuild => http://schemas.microsoft.com/developer/msbuild/2003
    ```
*  Patch
    ```
    = /msbuild:Project/msbuild:PropertyGroup/msbuild:DacVersion => "$(Build.BuildNumber)"
    = /msbuild:Project/msbuild:PropertyGroup/msbuild:DacApplicationName => "TestSQLServerDBProj$(Build.BuildNumber)"
    ```

In addition, depending on the format of your `BuildNumber` it might not build afterwards. `DacVersion` must have a 4 number format `0.0.0.0`. 

At Geek Learning, we use GitVersion to generate our semantic version number, we use Major, Minor and Patch for the 3 first numbers. We use our (Encode Semver to Integer)[https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-semver] to generate the last number. 

@asiffermann we should definitely turn this into a guide soon !

**Comment by asiffermann** [comment]
@sandorfr : I was thinking exactly the same thing as I just read the issue :)

**Comment by sandorfr** [comment]
@brett3210 have you resolved your issue?

**Comment by brett3210** [comment]
Yes, thank you for your assistance, and your prompt turnaround.
