### ISSUE TITLE
Missing write permissions on MacOS build agent

### ISSUE THREAD

**Issue by DibranMulder** [geeklearningio/gl-vsts-tasks-file-patch#20]
I keep getting this error, after the file has been patched:

> 2017-02-15T11:09:32.5701450Z ##[error]Error: EACCES: permission denied, open '/Developer/HostedBuildAgent/_work/1/s/MobileProject/Info.plist'

I can work around this with by adding write rights to the work folder of my MacOs build agent:

`chmod -R +rw _work`

However after cleaning the code I have to allow the rights again. Please use the same solution as the ReplaceTokens plugin, they use shelljs to modify the permissions prior to updating the file, look at this line of code:

https://github.com/colindembovsky/cols-agent-tasks/blob/master/Tasks/ReplaceTokens/replaceTokens.ts#L99

**Comment by sandorfr** [comment]
I'm quite short on time at the moment, but I'll be glad to accept a PR.

That said, I'm not sure to understand in what case you need this as I'm using the task daily on MacOs build agents without any hassle of such sort.

**Comment by DibranMulder** [comment]
I'm also not sure what's causing this issue, it might be that I'm using TFVC instead of GIT but I'm not sure. Anyway I'll try to find some time and create a PR.

**Comment by sandorfr** [comment]
Ah... as far as I remember, TFVC marks files as readonly until checkout... this sucks so much. Anyway, that would be improvement to address this.

**Comment by sandorfr** [comment]
This will be published as part of 1.3 Release
