### ISSUE TITLE
Cannot create package Error: Part Name 'Tasks/XmlPatch/node_modules/xpath/docs/function resolvers.md' is invalid.

### ISSUE THREAD

**Issue by wertzui** [geeklearningio/gl-vsts-tasks-file-patch#27]
I get the following error when I try to run `npm run package`

Failed to create extensions.
C:\Repos\gl-vsts-tasks-file-patch\node_modules\gl-vsts-tasks-build-scripts\package.js:106
        throw err;
        ^

Error: Command failed: tfx extension create --root "C:\Repos\gl-vsts-tasks-file-patch\.BuildOutput\production" --manifest-globs "C:\Repos\gl-vsts-tasks-file-patch\.BuildOutput\production\vss-extension.json" --output-path "C:\Repos\gl-vsts-tasks-file-patch\.BuildOutput\production"
error: Error: Part Name 'Tasks/XmlPatch/node_modules/xpath/docs/function resolvers.md' is invalid. Please check the following:
error: 1. No whitespace or any of these characters: #^[]<>?
error: 2. Cannot end with a period.
error: 3. No percent-encoded / or \ characters. Additionally, % must be followed by two hex characters.

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)

**Comment by sandorfr** [comment]
This should be fixed with the latest version thanks to modclean. Have you tried it recently?

**Comment by sandorfr** [comment]
I'm closing this feel free to reopen if you have any additional information
