### ISSUE TITLE
Patching a path with a drive letter is failing

### ISSUE THREAD

**Issue by dishmal** [geeklearningio/gl-vsts-tasks-file-patch#32]
I have to put a path like C:\blah\deblah and when I patch that as a variable, it fails with the following error:

2017-07-25T15:47:27.8618769Z = /My/Setting => "C:\Software\Blah\DeBlah" 
2017-07-25T15:47:27.8775006Z SyntaxError: Unexpected token S 
2017-07-25T15:47:27.8775006Z ##[error]SyntaxError: Unexpected token S

So it is somehow crashing out on the path of C:\ and expecting that to be the end of it even though my variable is set up properly.  (All my other ones translate properly, it is only this one.)

**Comment by sandorfr** [comment]
yes, you need to escape your path as the right part of the `=>` is JSON (so you can pass an object) : `C:\\Software\\Blah\\DeBlah`
