### ISSUE TITLE
Suppress patch warning messages or make them informational

### ISSUE THREAD

**Issue by jdshkolnik** [geeklearningio/gl-vsts-tasks-file-patch#41]
Hi,

My builds are being cluttered by warning messages like:

Couldn't apply patch to file: somefilepath1
Couldn't apply patch to file: somefilepath2
Couldn't apply patch to file: somefilepath3
Couldn't apply patch to file: somefilepath4
Couldn't apply patch to file: somefilepath5

The messages are legit in the sense that those files didn't have a node matching the criteria but I'd think that's more informational than it is a warning.

**Comment by sandorfr** [comment]
I'm considering replacing SkipErrors option by a dropdown, `Report Patch Errors As` with a dropdown including Error/Warning/Info, so everyone can pick whatever best suits his needs.

**Comment by jdshkolnik** [comment]
Until you do that, would you be willing to simply change those tl.warning calls to console.log?

**Comment by sandorfr** [comment]
@jdshkolnik no, i won't do that change as in most cases this indicates a wrong matching pattern selecting incompatible files that shouldn't be patched. It can happened because someone introduced new files and the pattern was not restrictive enough. 

However if you feel like tackling it a PR is always welcome.

**Comment by jdshkolnik** [comment]
Tackling which thing? I want to make sure we agree on the minimum requirements so no time is wasted. How do you envision this?

**Comment by jdshkolnik** [comment]
Hi @sandorfr

I'd like to do a pull request when I have time but I don't want to work on something you won't allow through.

**Comment by sandorfr** [comment]
Currently the switch from error to warning is done with the SkipErrors switch:
https://github.com/geeklearningio/gl-vsts-tasks-file-patch/blob/c83b92d2fdf8bf13e76ce300427df0ebc5a3363b/Tasks/JsonPatch/task.json#L93-L98

An approach for me would be to have a new conditional dropdown Field when SkipErrors is selected which would offer `Warning`, `Info`, `Nothing` with a default to Warning.
This https://github.com/geeklearningio/gl-vsts-tasks-file-patch/blob/c83b92d2fdf8bf13e76ce300427df0ebc5a3363b/Common/Node/patchProcess.ts#L65 should be changed to behave according to that setting.

**Comment by jdshkolnik** [comment]
It would be easier to change the SkipErrors boolean to a picklist like this:

Treat errors as _________ (**errors**, warnings, information, nothing)

**Comment by sandorfr** [comment]
Thanks for the PR, I'll aim at shipping a major version (since there a parameter change) by the end of the week.

**Comment by jdshkolnik** [comment]
@sandorfr Are you seeing the new picklist? Mine is still showing as a checkbox.

**Comment by sandorfr** [comment]
it's not published yet.

**Comment by sandorfr** [comment]
hello, it has been published as a 3.0 preview. So you need to update the version of your task in your build definition. 
Thanks
