### ISSUE TITLE
Normalize all brackets in a file path or glob pattern

### ISSUE THREAD

**Issue by AndreVasilev** [geeklearningio/gl-vsts-tasks-file-patch#43]
Good day!

I am trying to patch .plist file at path, which contains brackets in it's name. So, regex, that is generated from working directory + target filter, not matches any files to patch.

See logs in [attachment](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/files/1382274/3_Patch.files.Info.plist.txt)

It would be great, if you could fix this.

Respectfully,
Andrey

**Comment by sandorfr** [comment]
We didn't plan for bracket in file names :( I see the cause of the issue and several ways of fixing it. However this will require some testing so I can't make any promise on a deadline. 

meanwhile you can easily fix that by setting your search directory to $(Build.SourcesDirectory) and using an escaped pattern to match the file. For instance:
```
Wallet-iOS\(ObjC\)/Wallet/Wallet/Configuration Plists/Info.plist
```

or easier

```
**/Configuration Plists/Info.plist
```

**Comment by AndreVasilev** [comment]
Perfect solution for me
Thank you!
