### ISSUE TITLE
Unclear mapping xmlnamespace

### ISSUE THREAD

**Issue by maldworth** [geeklearningio/gl-vsts-tasks-file-patch#47]
I have this XML file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <!-- Required elements-->
        <id></id>
        <version></version>
        <description></description>
        <authors></authors>

        <!-- Optional elements -->
        <!-- ... -->
    </metadata>
    <!-- Optional 'files' node -->
</package>
```

and I have this slick syntax

`= /package/metadata/version => "1.1.0"`

It will fail. But if I remove the `xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd"`
it will pass.

what value do I have to pass into the build tasks `Xml Namespaces (As a Json map)` in order to get it to work with the namespace still in tact?

Thank you

**Comment by sandorfr** [comment]
I think it's pretty clear from the sample provided here : https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/Patch-XML-Files

You need to define a tag for you nampespace
```
nu => http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd
```

and use qualified names in you Xpath query:
```
= /nu:package/nu:metadata/nu:version => "1.1.0"
```

**Comment by maldworth** [comment]
Thank you. I had seen that page, and had tried the namespace on just package but it didn't work. I guess I didn't realize that I had to put the namespace prefix at every level `/nu:package/nu:<etc>/nu:<etc>`

I think maybe having the sampletest.xml file present on the wiki would have helped me figure that out. I would offer to submit a PR for the wiki page, but I don't think they allow PRs.

**Comment by sandorfr** [comment]
Yes wiki experience sucks for external contribs :( we have plans to switch to a documentation repos for our extensions with docfx, but stuff take time.
