### ISSUE TITLE
Patching JSON files fail while filtering the array elements

### ISSUE THREAD

**Issue by Prashanth-PS** [geeklearningio/gl-vsts-tasks-file-patch#49]
= /resources/0/resources[?(@.name=='LS_HTTP_ERS’)]/properties/typeProperties/username => "USERRRRRRR" 

The above syntax is not working when trying to patch a json file from VSTS task, could you please help get this working

**Comment by Prashanth-PS** [comment]
Hello Sandorfr,
The same task works when I use  
= /resources/0/resources/4/properties/typeProperties/username => "USERRRRRRR"

Though, it fails to identify the 4th array element with the given name
 Also I have verified that the jsonpath is valid on jsonpath.com and it is jsonpath rather than xpath
$..resources[0].resources[?(@.name=='LS_HTTP_ERS')].properties.typeProperties.username

if they are not correct, can you please suggest what is the correct way of patching a json file with array objects

**Comment by sandorfr** [comment]
The task is using jsonpatch which uses json pointers (
https://tools.ietf.org/html/rfc6901 )

JsonPath is another emerging standard which is not supported.
