### ISSUE TITLE
Patch JSON file with a forward slash in the key

### ISSUE THREAD

**Issue by k-schneider** [geeklearningio/gl-vsts-tasks-file-patch#50]
This doesn't seem to work.  I'm trying to do a patch similar to the following and it fails with `OPERATION_PATH_UNRESOLVABLE`.

```json
{
  "test": {
    "/baz": "qux",
    "foo": "bar"
  }
}
```

```json
[
  { "op": "replace", "path": "/test/~1baz", "value": "boo" }
]
```

**Comment by sandorfr** [comment]
I just published version `4.0.0` which does include a test for this case allowing me to be sure that this is not an issue anymore:
https://github.com/geeklearningio/gl-vsts-tasks-file-patch/blob/6df3549a80b3589fd33913626528b1ce49a01d80/Tests/JsonPatch/jsonPatcher.spec.ts#L38-L64
