### ISSUE TITLE
It seems, this task needs Node/npm on the agent machine. Is it true?

### ISSUE THREAD

**Issue by Geekays** [geeklearningio/gl-vsts-tasks-file-patch#52]
It seems, this task needs Node/npm on the agent machine. Is it true?

**Comment by asiffermann** [comment]
Hi @Geekays,

Yes, those tasks do need the build agent to have the "npm" capability.
All hosted agents have this capability, and any custom agent designed to build applications developed with recent technologies should have it too.

But, as Node is being bundled with the agent (in the "external" folder), I'm not sure that the explicit demand is mandatory in our tasks. We should test if we can remove it.

**Comment by sandorfr** [comment]
Yes I’m pretty sure we can remove it.

**Comment by brett3210** [comment]
We would like to use the "File Patch Build and Release Tasks" in our VSTS Release Definitions now.  However, we are using the VSTS "Deployment Group" Release Agents (https://docs.microsoft.com/en-us/vsts/pipelines/release/deployment-groups/?view=vsts), whereby the VSTS Agents are installed on every target machine (i.e. machine we're deploying our application to from the VSTS Release Definition).  Therefore, we don't want to have to install/manage NPM on every target machine through all of our environments.  

When do you think you'll be able to remove the dependency on NPM?  We'd really appreciate it if the dependency could be removed as soon as possible please.

**Comment by Geekays** [comment]
Thanks for update. I wish to use it on a private agent. And from the discussion here, I believe, I need to have node/npm on the agent machine as well.

**Comment by asiffermann** [comment]
I will test the removal of the demand today and let you know asap when the new version will be available on the marketplace!

**Comment by asiffermann** [comment]
All tests are green 👍
The extension is now published without any demand, you should be able to execute all tasks on any agent ([release 3.1.0](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/releases/tag/3.1.0) or [version 3.1.999 on the MarketPlace](https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-file-patch)).

I let you close this issue if it is resolved for you 😉

**Comment by brett3210** [comment]
Thank you very much

**Comment by asiffermann** [comment]
11 days later, I suppose this issue is resolved 😉

**Comment by Geekays** [comment]
Thanks for all the support. This is resolved.
