### ISSUE TITLE
JSON file doesn't support Comments

### ISSUE THREAD

**Issue by dvoituron** [geeklearningio/gl-vsts-tasks-file-patch#54]
I know that JSON does not provide syntax for comments.
But Microsoft allow to use '//' to comment text in a JSON file, and this text will be ignored.

When I create a JSON file with this comment symbols, my .Net project is working fine, but I receive an error **Couldn't apply patch to file**.

Example
``` 
{
  "AppSettings": {
    // First comment
    "Key": "value",
    "JwtExpirationMinutes": 60 // Second comment
  }
}

```

Can you add this new feature ?

Thanks

**Comment by sandorfr** [comment]
Have you tried to tick the parse JSON5 syntax checkbox. It should allow comments to be parsed

**Comment by dvoituron** [comment]
It's working using the flag "Use JSON 5". Thanks
