### ISSUE TITLE
Couldn't apply patch to file

### ISSUE THREAD

**Issue by loic-guenin** [geeklearningio/gl-vsts-tasks-file-patch#55]
Hello

I am trying to patch a xml file (the one uploaded as ApplicationInsights.txt)

[ApplicationInsights.txt](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/files/2331526/ApplicationInsights.txt)

The patch content is:
= /ApplicationInsights/InstrumentationKey => "#{AppinsightsKey}#"

However the patch is not applied and I have a message explaining that `/ApplicationInsights/InstrumentationKey was not found`
Do I miss something?

regards

Loïc

**Comment by sandorfr** [comment]
The syntax of your variable is weird didn’t you intend to write
$(AppInsightsKey)

**Comment by loic-guenin** [comment]
Hello, thank you very much for your quick answer

In fact I am using then this vsts task 
[Replace Tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens)
That's why I use this weird syntax  :)
But I don't think this is the cause of my problem... Do you think so?

**Comment by sandorfr** [comment]
Your document has a namespace so you need to have the dns mapping and your
xpath need to be updated accordingly.

https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/Patch-XML-Files

**Comment by loic-guenin** [comment]
ok thank you very much
