### ISSUE TITLE
Array of objects within JSON, how to solve that?

### ISSUE THREAD

**Issue by ClintHuijbers** [geeklearningio/gl-vsts-tasks-file-patch#56]
Dear Sir/Madam,

First of all, thanks for creating and sharing this extension with us.
I got it work for a simple example ('contentVersion' as seen below):
= /contentVersion => "1.2.3.4"

But I actually want to replace the value for 'host' with a parameter (e.g. "[parameters('FileShare_test_host')]"):
= /resources/properties/typeProperties/host => "[parameters('FileShare_test_host')]"

How do I do that?
Thanks a lot!

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
	{...},
        {
            "name": "[concat(parameters('factoryName'), '/FileShare_test')]",
            "type": "Microsoft.DataFactory/factories/linkedServices",
            "apiVersion": "2018-06-01",
            "properties": {
                "annotations": [],
                "type": "FileServer",
                "typeProperties": {
                    "host": "\\\\test.file.core.windows.net\\sources",
                    "userId": "[parameters('FileShare_test_properties_typeProperties_userId')]",
                    "password": {
                        "type": "SecureString",
                        "value": "[parameters('FileShare_test_password')]"
                    }
                }
            },
            "dependsOn": []
        },
	{...},
	{...}
    ]
}

**Comment by asiffermann** [comment]
Hi @ClintHuijbers,

[TL;DR]
`= /resources/0/properties/typeProperties/host => "[parameters('FileShare_test_host')]"`

You can point to an item within an array only with its index ; I don't know if it will fit your needs, but there is no other way using [JSON Patch](http://jsonpatch.com/).

You can use online tools to test you patches like this one : https://json-schema-validator.herokuapp.com/jsonpatch.jsp
You can even find the correct patch to use with this [other online tool](https://json-patch-builder-online.github.io/) from your current and desired states of your JSON fragment.

Hope that helps!

**Comment by sandorfr** [comment]
Yes that's one of the limitations of JsonPatch standard. I feel like a version of JSONPatch based on JsonPath instead of JsonPointers would help with such cases. However it's not a small task, as there is no library doing that out of the box
