### ISSUE TITLE
Xpath not working

### ISSUE THREAD

**Issue by bernd70** [geeklearningio/gl-vsts-tasks-file-patch#57]
Hi,

i am trying to patch a csproj File (XML format). There are several PropertyGroup entries which can be distinguised by a Condition attribute. Within the PropertyGroup for my Build Configuration (release) I want to patch a xml node value.

So the "Patch Content" value is:

`= /Project/PropertyGroup[contains(@Condition, 'Release')]/DebugType => "pdbonly"`

If I test the XPath against my csproj file it works fine but using the extension I get the error: /Project/PropertyGroup[contains(@Condition, 'Release')]/DebugType was not found.

Is contains() not supported or am I doing something wrong?

Thanks
Bernd

**Comment by sandorfr** [comment]
It should work. 
Can you provide the full source file?

**Comment by bernd70** [comment]
Here you go:

`<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <ConfigurationDataOmitted/>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <AndroidSupportedAbis />
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <BundleAssemblies>false</BundleAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>value-to-be-set</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <EnableProguard>true</EnableProguard>
    <BundleAssemblies>false</BundleAssemblies>
    <AotAssemblies>true</AotAssemblies>
    <AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <AndroidSupportedAbis>
    </AndroidSupportedAbis>
  </PropertyGroup>
</Project>`

I omitted some nonrelevant data.

Regards
Bernd

**Comment by bernd70** [comment]
Allright, this was it, thank you.

Actually the namespace is only necessary for Project and PropertyGroup, not for DebugType.

Regards
Bernd
