### ISSUE TITLE
Unable to replace attribute in AndroidManifest.xml

### ISSUE THREAD

**Issue by bhump** [geeklearningio/gl-vsts-tasks-file-patch#59]
I'm trying to replace an attribute in an AndroidManifest.xml file. 
I'm trying 

> = /manifest/application/meta-data[@android:name='ConfigFile']/@android:value => "UAT"

I get the error "Couldn't apply patch to file: ../../AndroidManifest.xml

The line I'm trying to patch is.. `<meta-data android:name="ConfigFile" android:value="Sandbox" />`
Is there something that is missing?

**Comment by roizentner** [comment]
It looks like you have an XML namespace named _android_.
Did you remember to specify it in the XML Namespace parameter of the task?

**Comment by p4dev** [comment]
Having a similar issue here. I have the XML namespace parameter in the task and have the patch content argument:
`JsonPatchContent: = /manifest/android:versionName => "Foo.Bar`

**Comment by sandorfr** [comment]
Please provide the debug logs.

**Comment by p4dev** [comment]
@sandorfr I was able to achieve my goal using these two lines:

`        Namespaces: 'android => http://schemas.android.com/apk/res/android'
        JsonPatchContent: '= /manifest/@android:versionName => "$(VersionNumber)"'`

**Comment by sandorfr** [comment]
It's why I ask for the trace beacause you most likely didn't define the android namespace.

**Comment by sandorfr** [comment]
Yes,  I guess you didn't define the namespaces in your first attempt? I guess I need to provides some recipes in the docs for common use cases like this. People using Yaml could just copy paste them.

**Comment by p4dev** [comment]
I wouldn't close this issue as I am not OP, I just tagged on because I was having a similar issue. Where I went wrong was I didn't define the URL that the android namespace points to. It would be incredibly helpful if you could base your Wiki pages on an xml/plist/json files that are available in the repo. Or even add the structure of one to a readme if you don't want needless clutter in your repo.
