### ISSUE TITLE
Feature: checkbox "create file if doesn't exists"

### ISSUE THREAD

**Issue by mvidailhet** [geeklearningio/gl-vsts-tasks-file-patch#6]
It would be useful to have the ability to create the file if it doesn't exist

**Comment by sandorfr** [comment]
I'm curious about the use case as this would not be compatible with globbing.

**Comment by sandorfr** [comment]
Will be addressed by creating a new task in files extension : https://github.com/geeklearningio/gl-vsts-tasks-files/issues/2
