### ISSUE TITLE
Replace '=' operator if path exists in target files

### ISSUE THREAD

**Issue by Anthony-Breneliere** [geeklearningio/gl-vsts-tasks-file-patch#65]
Hello,

Is there a way to replace value only in case the path exists in the target file ?

I replace value for deployment process but I use gl-vsts-tasks-file-patch in a Task group that is used for multiple services, to patch azuredeploy.parameters.json.

It is possible one of the path/value to replace does not exists in a service file, but does exists in other service's parameters file.

So I need 
= /path/tovalue => "value"  does not throw an error in case /path/tovalue does not exists in the target file.

Is that possible ?

**Comment by sandorfr** [comment]
Your best chance at achieving this is to use a JsonPatch test and continue on task failure
