### ISSUE TITLE
Same configuration doesn't work on version 4.* for Patch XML Files

### ISSUE THREAD

**Issue by Skoucail** [geeklearningio/gl-vsts-tasks-file-patch#70]
The configuration below for patching xml (nuspec) files in all folders always worked in versions 3.*
When trying out the new version 4.* i got the error no files where patched. Nothing else changed only the version of the task.

![image](https://user-images.githubusercontent.com/20516786/76314892-ed7b6880-62d7-11ea-80ed-a19edf57e023.png)

**Comment by sandorfr** [comment]
Hello, 

Thanks for reporting this. I deployed a bugfix, let me know how it goes!

Kind regards

**Comment by Skoucail** [comment]
> Hello,
> 
> Thanks for reporting this. I deployed a bugfix, let me know how it goes!
> 
> Kind regards

Thanks, i just tested  this and seems to be working again. 👍

**Comment by sandorfr** [comment]
Thanks for the update!
