### ISSUE TITLE
anyone have a reasonable example of patching an xml file

### ISSUE THREAD

**Issue by Nathan187** [geeklearningio/gl-vsts-tasks-file-patch#90]
Before opening an issue please [read this](https://github.com/geeklearningio/gl-vsts-tasks-file-patch/wiki/How-to-Report-an-issue).

# Are you reporting a bug or a feature request ?
* [ ] Bug
* [ ] Feature request

# Description

the is no clear documentation on how to patch an xml file (what if you want to add new tags and data?)  there are no clear examples on how to do such thing

# Expected behavior

a thorough document with decent examples would be nice

# Reproduction

 n/a

```
MANDATORY FOR BUGS: Insert debug trace. If you don't provide it it makes it hard to understand what you are facing. 
To get a meaningful Trace don't forget to set System.Debug variable to true when queuing.
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository*

# System information

**VSTS or TFS:**
* [x ] VSTS  (azure devops)
* [ ] TFS

**Agent:**
* [x ] Hosted
* [ ] Custom

**OS:**
* [x ] Windows
* [ ] Mac
* [ ] Linux

**Comment by sandorfr** [comment]
You can look at the tests for a couple of examples

https://github.com/geeklearningio/gl-vsts-tasks-file-patch/blob/master/Tests/XmlPatch/xmlPatcher.spec.ts

**Comment by Nathan187** [comment]
definitely helped, resolved my issue...RTFM

(was using this task in azure devops pipelines.  first thing i was doing wrong was, i was trying to create new tags all in one line instead of separating them out properly.  second thing i was doing wrong was performing the task on a file after publishing the artifact.  patch the file before)
